---
title: "EDA"
author: "Brock Friedrich"
date: "September 23, 2018"
---

```{r setup, include=FALSE}
require(tidyverse)
require(magrittr)
require(kableExtra)
require(car)
require(knitr)
require(summarytools)
require(grid)
require(gridExtra)
require(svglite)
# library(AER)
# require(effects)

# set knitr output options for consistent figures
knitr::opts_chunk$set(fig.width=12,
                      fig.height=8,
                      fig.path='../figs/',
                      warning=FALSE,
                      message=FALSE,
                      echo = TRUE,
                      #root.dir = normalizePath(".."),
                      #child.dir = normalizePath(".."),
                      cache = FALSE,
                      results = 'html',
                      # results = 'asis',
                      collapse = TRUE
                      # tidy = TRUE
)


# 
# # set visual theme for the project
# ggplot2::theme_set(ggplot2::theme_bw())
# ggplot2::theme_update(plot.title = ggplot2::element_text(hjust = 0.5))

#prevent implicit conversion to scientific notation
options(scipen = 999)
options(knitr.table.format = "html")
#disable column wrapping
options(width=100) 

# set options for descriptive statistics
st_options('escape.pipe', TRUE)
st_options('descr.stats', c("mean", "sd", "min", "med", "max", "Q1", "Q3", "N.Valid", "pct.valid", "iqr", "skewness", "kurtosis"))
st_options('descr.transpose', TRUE)
st_options('style', "rmarkdown")


```


```{r import_functions}


summarize_frame <- function(frameframe)
{
    #returns table of summary statistics for each numeric column in dataframe
    summarytools::descr(frameframe, transpose = TRUE)
}


standardize_names <- function(frameframe) 
{  
    # reformats column names to a regularized format wiuth:
    # - punctuation removed
    # - all letters lowercase
    # - no leading or trailing whitespace
    frameframe %>% 
    rename_all(gsub, pattern = '[[:punct:] ]+', replacement = '') %>%
    rename_all(tolower) %>%
    rename_all(trimws)

}

table_styler <- function(frameframe)
{
  
    # returns table formatted ready for display
    kable(frameframe) %>%
    kable_styling(position = "center"
                 , full_width = TRUE
                 , bootstrap_options = "striped")

}

```




```{r read_train_data, results = 'html'}

getwd()


# read train data and ocnvert to tibble frame
train = read.csv('./../data/train.csv') %>% as.tibble()

# train %>% colnames()

# View column names and types
train %>% str()

train %>% head()
```



```{r summarize_train}

# summarize train
train.summary = descr(train) %>% round(2)
train.summary <- train.summary %>% add_rownames() %>%rename("column_name" = 1)
# Write summary to file
train.summary %>% write.csv('./../data/train_summary.csv')
```


```{r}



train.summary

```



```{r fig.height = 35, fig.width = 16}


# Boxplot per Feature
ggplot(train.summary, aes(x = as.factor(column_name))) +
  geom_boxplot(aes(
      lower = Mean - Std.Dev, 
      upper = Mean + Std.Dev, 
      middle = Mean, 
      ymin = Mean - 3*Std.Dev, 
      ymax = Mean + 3*Std.Dev),
    stat = "identity") +
  ggtitle("Feature Variance") +
  xlab("Features") +
  ylab("Variation") +
  theme(text = element_text(size=10),
        axis.text.x = element_text(angle=90, vjust=0.5),
        axis.text.y = element_text(size=8, margin = margin(t = 20, b = 20, l = 20)),
        plot.title = element_text(hjust = 0.5, size = 16)) +
  ylim(-1000, 1000) +
coord_flip()
```



```{r}

# train %>% ncol()

c = colors(distinct = TRUE)





inc <- 5
u.bind <- train %>% ncol()
l.bind <- u.bind - inc

while (u.bind > inc)
{
  
  # Get random color name from default palette 
  c.s <- c[sample(2:length(c), 1)]
  
  # Open PNG device
  png(filename = sprintf('./../figs/%s.png'
                         , filename = train[,l.bind:u.bind] %>% 
                              colnames() %>% 
                              paste(collapse="---"))
      , width = 10
      , height = 10
      , units = 'in'
      , res = 300)
  
  # Plot 
  scatterplotMatrix(train[,l.bind:u.bind] %>% select_if(is.numeric)
                    , smooth=FALSE
                    , diagonal="histogram"
                    , col = c.s) 
  
  # Close device
  dev.off()

  sprintf("Generated Image: %s : %s", l.bind, u.bind)
  
  # Decrement binders
  u.bind <- u.bind - (inc+1)
  l.bind <- l.bind - (inc+1)
  
}

# Plot remainder of columns
if (u.bind > 0)
{
  
  # Get random color name from default palette 
  c.s <- c[sample(2:length(c), 1)]
  
  # Open PNG device
  png(filename = sprintf('./../figs/%s.png'
                         , filename = train[,l.bind:u.bind] %>% 
                              colnames() %>% 
                              paste(collapse="---"))
    , width = 10
    , height = 10
    , units = 'in'
    , res = 300)
  
  # Plot 
  scatterplotMatrix(train[,l.bind:u.bind] %>% select_if(is.numeric)
                    , smooth=FALSE
                    , diagonal="histogram"
                    , col = c.s) 
  
  # Close device
  dev.off()
  
  
  sprintf("Generated Image: %s : %s", l.bind, u.bind)
  
  # Decrement binders
  u.bind <- u.bind - (inc+1)
  l.bind <- l.bind - (inc+1)  
  
  
}



  # Save plot to file. Filename is a concatenation of the features included in the plot
  # ggsave(filename = train[,l.bind:u.bind] %>% colnames() %>% paste(collapse="---")
  #        , plot = p
  #        , path = './../figs'
  #        , height = 30
  #        , width = 30
  #        , device = "svg"
  #       )
  

```

# Modelling


```{r}
# train %>%
#   dplyr::select(-price_doc) %>% 
#   colnames() %>% 
#   paste(collapse="+")

# https://www.statmethods.net/stats/regression.html
# All Subsets Regression
library(leaps)
# lps <- leaps(x = train %>% dplyr::select(-price_doc)
#             ,y = train["price_doc"]
#             ) 
#   
  
lps <-  regsubsets(price_doc~id+timestamp+full_sq+life_sq+floor+max_floor+material+build_year+num_room+kitch_sq+state+product_type+sub_area+area_m+raion_popul+green_zone_part+indust_part+children_preschool+preschool_quota+preschool_education_centers_raion+children_school+school_quota+school_education_centers_raion+school_education_centers_top_20_raion+hospital_beds_raion+healthcare_centers_raion+university_top_20_raion+sport_objects_raion+additional_education_raion+culture_objects_top_25+culture_objects_top_25_raion+shopping_centers_raion+office_raion+thermal_power_plant_raion+incineration_raion+oil_chemistry_raion+radiation_raion+railroad_terminal_raion+big_market_raion+nuclear_reactor_raion+detention_facility_raion+full_all+male_f+female_f+young_all+young_male+young_female+work_all+work_male+work_female+ekder_all+ekder_male+ekder_female+X0_6_all+X0_6_male+X0_6_female+X7_14_all+X7_14_male+X7_14_female+X0_17_all+X0_17_male+X0_17_female+X16_29_all+X16_29_male+X16_29_female+X0_13_all+X0_13_male+X0_13_female+raion_build_count_with_material_info+build_count_block+build_count_wood+build_count_frame+build_count_brick+build_count_monolith+build_count_panel+build_count_foam+build_count_slag+build_count_mix+raion_build_count_with_builddate_info+build_count_before_1920+build_count_1921.1945+build_count_1946.1970+build_count_1971.1995+build_count_after_1995+ID_metro+metro_min_avto+metro_km_avto+metro_min_walk+metro_km_walk+kindergarten_km+school_km+park_km+green_zone_km+industrial_km+water_treatment_km+cemetery_km+incineration_km+railroad_station_walk_km+railroad_station_walk_min+ID_railroad_station_walk+railroad_station_avto_km+railroad_station_avto_min+ID_railroad_station_avto+public_transport_station_km+public_transport_station_min_walk+water_km+water_1line+mkad_km+ttk_km+sadovoe_km+bulvar_ring_km+kremlin_km+big_road1_km+ID_big_road1+big_road1_1line+big_road2_km+ID_big_road2+railroad_km+railroad_1line+zd_vokzaly_avto_km+ID_railroad_terminal+bus_terminal_avto_km+ID_bus_terminal+oil_chemistry_km+nuclear_reactor_km+radiation_km+power_transmission_line_km+thermal_power_plant_km+ts_km+big_market_km+market_shop_km+fitness_km+swim_pool_km+ice_rink_km+stadium_km+basketball_km+hospice_morgue_km+detention_facility_km+public_healthcare_km+university_km+workplaces_km+shopping_centers_km+office_km+additional_education_km+preschool_km+big_church_km+church_synagogue_km+mosque_km+theater_km+museum_km+exhibition_km+catering_km+ecology+green_part_500+prom_part_500+office_count_500+office_sqm_500+trc_count_500+trc_sqm_500+cafe_count_500+cafe_sum_500_min_price_avg+cafe_sum_500_max_price_avg+cafe_avg_price_500+cafe_count_500_na_price+cafe_count_500_price_500+cafe_count_500_price_1000+cafe_count_500_price_1500+cafe_count_500_price_2500+cafe_count_500_price_4000+cafe_count_500_price_high+big_church_count_500+church_count_500+mosque_count_500+leisure_count_500+sport_count_500+market_count_500+green_part_1000+prom_part_1000+office_count_1000+office_sqm_1000+trc_count_1000+trc_sqm_1000+cafe_count_1000+cafe_sum_1000_min_price_avg+cafe_sum_1000_max_price_avg+cafe_avg_price_1000+cafe_count_1000_na_price+cafe_count_1000_price_500+cafe_count_1000_price_1000+cafe_count_1000_price_1500+cafe_count_1000_price_2500+cafe_count_1000_price_4000+cafe_count_1000_price_high+big_church_count_1000+church_count_1000+mosque_count_1000+leisure_count_1000+sport_count_1000+market_count_1000+green_part_1500+prom_part_1500+office_count_1500+office_sqm_1500+trc_count_1500+trc_sqm_1500+cafe_count_1500+cafe_sum_1500_min_price_avg+cafe_sum_1500_max_price_avg+cafe_avg_price_1500+cafe_count_1500_na_price+cafe_count_1500_price_500+cafe_count_1500_price_1000+cafe_count_1500_price_1500+cafe_count_1500_price_2500+cafe_count_1500_price_4000+cafe_count_1500_price_high+big_church_count_1500+church_count_1500+mosque_count_1500+leisure_count_1500+sport_count_1500+market_count_1500+green_part_2000+prom_part_2000+office_count_2000+office_sqm_2000+trc_count_2000+trc_sqm_2000+cafe_count_2000+cafe_sum_2000_min_price_avg+cafe_sum_2000_max_price_avg+cafe_avg_price_2000+cafe_count_2000_na_price+cafe_count_2000_price_500+cafe_count_2000_price_1000+cafe_count_2000_price_1500+cafe_count_2000_price_2500+cafe_count_2000_price_4000+cafe_count_2000_price_high+big_church_count_2000+church_count_2000+mosque_count_2000+leisure_count_2000+sport_count_2000+market_count_2000+green_part_3000+prom_part_3000+office_count_3000+office_sqm_3000+trc_count_3000+trc_sqm_3000+cafe_count_3000+cafe_sum_3000_min_price_avg+cafe_sum_3000_max_price_avg+cafe_avg_price_3000+cafe_count_3000_na_price+cafe_count_3000_price_500+cafe_count_3000_price_1000+cafe_count_3000_price_1500+cafe_count_3000_price_2500+cafe_count_3000_price_4000+cafe_count_3000_price_high+big_church_count_3000+church_count_3000+mosque_count_3000+leisure_count_3000+sport_count_3000+market_count_3000+green_part_5000+prom_part_5000+office_count_5000+office_sqm_5000+trc_count_5000+trc_sqm_5000+cafe_count_5000+cafe_sum_5000_min_price_avg+cafe_sum_5000_max_price_avg+cafe_avg_price_5000+cafe_count_5000_na_price+cafe_count_5000_price_500+cafe_count_5000_price_1000+cafe_count_5000_price_1500+cafe_count_5000_price_2500+cafe_count_5000_price_4000+cafe_count_5000_price_high+big_church_count_5000+church_count_5000+mosque_count_5000+leisure_count_5000+sport_count_5000+market_count_5000,data=train,nbest=10)
# view results 
summary(lps)
# plot a table of models showing variables in each model.
# models are ordered by the selection statistic.
plot(lps,scale="r2")
# plot statistic by subset size 
library(car)
subsets(lps, statistic="rsq")

```

```{r}

```






