---
title: "models"
author: "Brock Friedrich"
date: "September 29, 2018"
output: html_document
---


1. Identify the key objectives. 
2. Screen the available variables, deciding on a list that is sensitive to the objectives and excludes obvious redundancies. 3. Perform exploratory analysis, examining graphical displays and correlation coefficients. 
4. Perform transformations as necessary. 
5. Examine a residual plot after fitting a rich model, performing further transformations and considering outliers. 
6. Use a computer-assisted technique for finding a suitable subset of explanatory variables, exerting enough control over the process to be sensitive to the questions of interest. 
7. Proceed with the analysis, using the selected explanatory variables.

Ramsey, Fred; Schafer, Daniel. The Statistical Sleuth: A Course in Methods of Data Analysis (Page 355). Cengage Textbook. Kindle Edition. 



1. Predict price of specific property
    - Select model based on minimization of RMSLE

2. List of variables that are sensitive to the objectives, excluding obvious redundancies
  - 


price.doc~full.sq+life.sq+floor+max.floor+material+build.year+num.room+kitch.sq+state+product.type+sub.area+area.m+raion.popul+green.zone.part+indust.part+children.preschool+preschool.quota+preschool.education.centers.raion+children.school+school.quota+school.education.centers.raion+school.education.centers.top.20.raion+hospital.beds.raion+healthcare.centers.raion+university.top.20.raion+sport.objects.raion+additional.education.raion+culture.objects.top.25+culture.objects.top.25.raion+shopping.centers.raion+office.raion+thermal.power.plant.raion+incineration.raion+oil.chemistry.raion+radiation.raion+railroad.terminal.raion+big.market.raion+nuclear.reactor.raion+detention.facility.raion+full.all+male.f+female.f+young.all+young.male+young.female+work.all+work.male+work.female+ekder.all+ekder.male+ekder.female+x0.6.all+x0.6.male+x0.6.female+x7.14.all+x7.14.male+x7.14.female+x0.17.all+x0.17.male+x0.17.female+x16.29.all+x16.29.male+x16.29.female+x0.13.all+x0.13.male+x0.13.female+raion.build.count.with.material.info+build.count.block+build.count.wood+build.count.frame+build.count.brick+build.count.monolith+build.count.panel+build.count.foam+build.count.slag+build.count.mix+raion.build.count.with.builddate.info+build.count.before.1920+build.count.1921.1945+build.count.1946.1970+build.count.1971.1995+build.count.after.1995+metro.min.avto+metro.km.avto+metro.min.walk+metro.km.walk+kindergarten.km+school.km+park.km+green.zone.km+industrial.km+water.treatment.km+cemetery.km+incineration.km+railroad.station.walk.km+railroad.station.walk.min+railroad.station.avto.km+railroad.station.avto.min+public.transport.station.km+public.transport.station.min.walk+water.km+water.1line+mkad.km+ttk.km+sadovoe.km+bulvar.ring.km+kremlin.km+big.road1.km+big.road1.1line+big.road2.km+railroad.km+railroad.1line+zd.vokzaly.avto.km+bus.terminal.avto.km+oil.chemistry.km+nuclear.reactor.km+radiation.km+power.transmission.line.km+thermal.power.plant.km+ts.km+big.market.km+market.shop.km+fitness.km+swim.pool.km+ice.rink.km+stadium.km+basketball.km+hospice.morgue.km+detention.facility.km+public.healthcare.km+university.km+workplaces.km+shopping.centers.km+office.km+additional.education.km+preschool.km+big.church.km+church.synagogue.km+mosque.km+theater.km+museum.km+exhibition.km+catering.km+ecology+green.part.1000+prom.part.1000+office.count.1000+trc.count.1000+cafe.sum.1000.min.price.avg+cafe.sum.1000.max.price.avg+cafe.avg.price.1000+big.church.count.1000+church.count.1000+mosque.count.1000+leisure.count.1000+sport.count.1000+market.count.1000+green.part.2000+prom.part.2000+office.count.2000+trc.count.2000+cafe.sum.2000.min.price.avg+cafe.sum.2000.max.price.avg+cafe.avg.price.2000+big.church.count.2000+church.count.2000+mosque.count.2000+leisure.count.2000+sport.count.2000+market.count.2000+green.part.3000+prom.part.3000+office.count.3000+trc.count.3000+cafe.sum.3000.min.price.avg+cafe.sum.3000.max.price.avg+cafe.avg.price.3000+big.church.count.3000+church.count.3000+mosque.count.3000+leisure.count.3000+sport.count.3000+market.count.3000

```{r fig.width = 30, fig.height = 30}



train %>% select(price.doc, full.sq, life.sq, floor, max.floor, material, build.year, num.room, kitch.sq, state, product.type, sub.area, area.m, raion.popul, green.zone.part, indust.part, children.preschool, preschool.quota, preschool.education.centers.raion, children.school, school.quota, school.education.centers.raion) %>%
  mutate(price.log = log(price.doc)) %>%
  gather(-price.log, key = "var", value = "value") %>% 
  ggplot(aes(x = value, y = price.log)) +
    geom_point() +
    facet_wrap(~ var, scales = "free") +
    theme_bw()

ggsave("test.png", width = 30, height = 30, units = "in")

```





